name: Build composer image

on:
  push:
    branches:
      - master

    tags:
      - v*

env:
  IMAGE_NAME_BASE: base
  IMAGE_NAME_TEST: testing

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the composer base image
      run: |
        docker build base --tag $IMAGE_NAME_BASE

    - name: Build the composer testing image
      run: |
        docker build testing --tag $IMAGE_NAME_TEST

    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push images to docker hub
      run: |
        IMAGE_ID=${{ github.repository }}
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest

        echo "Pushing image $IMAGE_ID:$VERSION"
        docker tag $IMAGE_NAME_BASE $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION

        echo "Pushing image $IMAGE_ID:$VERSION-testing"
        docker tag $IMAGE_NAME_TEST $IMAGE_ID:$VERSION-testing
        docker push $IMAGE_ID:$VERSION-testing
